#!/usr/bin/python3

from flask import Flask, jsonify
import female_info

app = Flask(__name__)

@app.route('/')
def home():
    return "Welcome to Herware API"

@app.route('/about')
def about():
    return 'About page'

if __name__ == '__main__':
    app.run(debug=True)
